import { StyleSheet } from 'react-native';
import { brand, color } from '../../../../public/style/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.backgroundGray,
  },
  scrollContent: {
    paddingBottom: 16,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  logoText: {
    fontSize: 18,
    fontWeight: '800',
    color: brand.ibkDeepBlue,
    letterSpacing: -0.4,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    lineHeight: 34,
    letterSpacing: -0.6,
  },
  categorySection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 20,
  },
  categoryItem: {
    width: '25%',
    alignItems: 'center',
  },
  categoryCard: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: brand.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  categoryLabel: {
    fontSize: 12,
    color: '#232323',
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  bannerSection: {
    paddingHorizontal: 20,
    marginTop: 12,
  },
  banner: {
    height: 132,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  bannerGradientLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '55%',
    backgroundColor: '#6366F1',
  },
  bannerGradientRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '55%',
    backgroundColor: '#0891B2',
  },
  bannerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  bannerTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    lineHeight: 26,
  },
  bannerSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    marginTop: 6,
    lineHeight: 18,
  },
  bannerBadge: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  bannerBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  bannerBadgeAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    marginTop: 2,
  },
  bannerIndicator: {
    position: 'absolute',
    right: 12,
    bottom: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bannerIndicatorText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  promoRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 14,
    gap: 10,
  },
  promoCard: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: 'center',
    minHeight: 108,
    justifyContent: 'space-between',
    backgroundColor: brand.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  promoTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
    textAlign: 'center',
    lineHeight: 18,
  },
  activitySection: {
    marginHorizontal: 20,
    marginTop: 18,
    backgroundColor: brand.white,
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  activityTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: brand.ibkDeepBlue,
    marginBottom: 14,
  },
  activityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 11,
  },
  activityLabel: {
    fontSize: 14,
    color: '#4B5563',
  },
  activityValue: {
    fontSize: 14,
    fontWeight: '600',
    color: brand.ibkBlue,
  },
  activityDivider: {
    height: 1,
    backgroundColor: '#EEF2F7',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: brand.white,
    borderTopWidth: 1,
    borderTopColor: '#EEF2F7',
    paddingTop: 8,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    gap: 2,
  },
  bottomNavIcon: {
    fontSize: 18,
    color: '#9CA3AF',
    lineHeight: 22,
  },
  bottomNavIconActive: {
    color: brand.ibkBlue,
    fontWeight: '700',
  },
  bottomNavLabel: {
    fontSize: 10,
    color: '#9CA3AF',
    fontWeight: '500',
  },
  bottomNavLabelActive: {
    color: brand.ibkBlue,
    fontWeight: '700',
  },
});
